apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-deployment
  labels:
    app: cast-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
        - name: cast-service
          image: art2025/jenkins-exam-cast:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URI
              value: "postgresql://cast_user:cast_pass@cast-db:5432/cast_db"
